<div class="page-header">
    <h1>Staff Contract</h1>
    <div class="pull-right link-view" style="margin-top: -25px">
        <a href="/contract/assign-label" class="btn btn-warning pull-right">Manage label</a>
    </div>
</div>


<div class="table-responsive">
    <?php
        echo $this->render('contract/partials/list.phtml');
    ?>
</div>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>
<script>
    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 3,
        disableIfEmpty: true
    };
        
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
        multi();
    });

    $('.btn-send').click(function() {
        var _self = $(this);            
        _self.closest('tr').find('.label_replace').text("Đã in");         
    });

    function multi() {
        $('.multiselect').multiselect(options);
    }     
</script>