<link rel="stylesheet" type="text/css" href="/css/bootstrap-datetimepicker.min.css"/>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.checkboxtree.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/jquery.checkboxtree.css"/>
<style>
    select {
        max-width: 100%;
    }

    #tab_show label:not(.checkbox) {
        font-weight: bold;
    }

    .thumbnail {
        width: 100px;
        height: 100px;
        overflow: hidden;
        text-align: center;
        padding: 0;
        margin: auto;
        text-align: center;
    }

    .thumbnail i {
        font-size: 100px;
    }

    .thumbnail span {
        width: 100px;
        height: 100px;
    }

    .attachment_name {
        word-wrap: break-word;
        font-weight: bold;
        text-align: center;
    }

    #add_category_btn {
        margin-bottom: 9px;
    }

    .ui-widget-content .ui-icon {
        background-color: #ccc;
        border-radius: 2px;
    }

    .ui-widget-content .ui-icon:hover {
        cursor: pointer;
    }

    .tree input {
        margin-left: 4px;
    }

    .tree label {
        display: inline-block;
        padding-left: 4px;
    }

    .tree li:hover>label {
        background: #efe;
    }

    .ui-widget-content {
        background: none;
        border: none;
    }
    .loading-for-before{
        position: absolute;
        right: 200px;
        margin-top: 8px;
    }

    .modal {
        max-height: 500px;
        top: 14% !important;
        width: 450px;
    }

    .savedata{
        height: 30px;
    }
</style>

<div class="page-header">
    <?php if (isset($this->notification) and $this->notification):?>
        <h1>Edit notification</h1>
    <?php else:?>
        <h1>Create notification</h1>
    <?php endif;?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<div class="row-fluid">
    <div class="span12">
        <iframe name="frame" id="iframe" width="100%" style="display: none;border: none"></iframe>
        <form role="form" id="form" target="frame" action="<?php echo HOST.'manage/notification-save';?>" method="post">
            <div class="row-fluid">
                <div class="span12">
                    <p class="pull-right">
                        <input type="hidden" name="id" id="id" value="<?php isset($this->notification) and $this->notification and printf($this->notification->id);?>">
                        <button type="submit" id="submit_btn" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-danger" onclick="window.location='<?php echo HOST ?>manage/notification'">Go back</button>
                    </p>
                </div>
            </div>

            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_content" data-toggle="tab">Content</a></li>
                <li><a href="#tab_show" data-toggle="tab">Display to</a></li>
                <li><a href="#tab_time" data-toggle="tab">Set time</a></li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane active" id="tab_content">
                    <?php echo $this->render('manage/partials/tab-content.phtml') ?>
                </div>

                <div class="tab-pane" id="tab_show">
                    <?php echo $this->render('manage/partials/tab-show.phtml') ?>
                </div>

                <div class="tab-pane" id="tab_time">
                    <?php echo $this->render('manage/partials/tab-time.phtml') ?>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo HOST?>ckeditor/ckeditor.js"></script>
<script>
config = {};
config.toolbar = [
	{ name: 'clipboard', groups: [ 'clipboard', 'undo' ], items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
	{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
	{ name: 'about', items: [ 'Source' ] },
	'/',

	{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language' ] },
	{ name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
	{ name: 'insert', items: [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] },
	'/',
	{ name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
	{ name: 'colors', items: [ 'TextColor', 'BGColor' ] },
	{ name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
	{ name: 'others', items: [ '-' ] }
];

config.enterMode = CKEDITOR.ENTER_BR;
config.shiftEnterMode = CKEDITOR.ENTER_P;
CKEDITOR.replace( 'content' , config);
</script>
<script language="javascript" type="text/javascript" src="/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.tree').checkboxTree();
        $('.date').datetimepicker({
            weekStart: 1,
            clear: true,
            minView: '0',
            autoclose: true,
            format: 'dd/mm/yyyy hh:ii'
        });

        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();
            return false;
        });
    });

    function check_select_all(e) {
        $('.display-item').unbind('change');
        _self = $(e.target);
        type = _self.data('type');
        if (!type) return false;
        all_is_checked = true;
        $(type).each(function(index, el) {
            if (!$(el).prop('checked')) {
                all_is_checked = false;
                return false;
            }
        });
        $('[data-target="'+type+'"]').prop('checked', all_is_checked);
        $('.display-item').change(check_select_all);
    }

    function check_all(e) {
        _self = $(e.target);
        target = _self.data('target');
        if (!target) return false;
        $(target).prop('checked', _self.prop('checked'));
    }

</script>
