<div class="page-header">
    <h1>List Staff Check In</h1>
</div>

<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;

    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2">
                Report Excel
            </a>
        </div>
        <div  class="accordion-body" style="height: 0px;">
            <div class="accordion-inner">
            <form class="form-search form-horizontal" method="get" action="/staff">
            <div class="row">
                <div class="span5">
                    <div class="control-group">
                        <label for="name" class="span2">Name</label>
                        <input type="text" name="name" id="name" value="<?php echo $this->params['name'] ?>">
                    </div>
        
                    <div class="control-group">
                        <label for="code" class="span2">Code</label>
                        <input type="text" name="code" id="code" value="<?php echo $this->params['code'] ?>">
                    </div>
                    
                    <div class="control-group">
                        <label for="name" class="span2">Tháng</label>
                        <select name="month" class="p_month">
                        <?php
                            for($i = 1; $i <= 12; $i++)
                            {
                            ?>
                            <option <?php echo ($i == intval($this->params['month'])?" selected ":"") ?> value="<?php echo $i ?>">Tháng <?php echo $i ?></option>
                            <?php
                            }
                        ?>
                        </select>
                    </div>

                    <div class="control-group">
                        <label for="name" class="span2">Năm</label>
                        <input type="number" class="p_year" name="year" value="<?php echo $this->params['year'] ?>">
                    </div>
                </div> 


                <div class="span6">
                    <div class="control-group">
                        <label for="department" class="span2">Department</label>
                        <select name="department" id="department">
                            <option value>Choose</option>
                            <?php if (isset($this->recursiveDeparmentTeamTitle)): ?>
                                <?php foreach ($this->recursiveDeparmentTeamTitle as $item_id => $item):?>
                                    <option value="<?php echo $item_id;?>" <?php if (isset($this->params) and $this->params and $item_id==$this->params['department']):?>selected<?php endif;?>><?php echo $item['name'];?></option>
                                <?php endforeach;?>
                            <?php endif ?>
                        </select>
                    </div>

                    <div class="control-group">
                        <label for="team" class="span2">Team</label>
                        <select name="team" id="team" >
                            <option value>Choose</option>
                            <?php if ( isset($this->params) AND isset($this->recursiveDeparmentTeamTitle[$this->params['department']]['children'])): ?>
                                <?php foreach ($this->recursiveDeparmentTeamTitle[$this->params['department']]['children'] as $item_id => $item):?>
                                    <option value="<?php echo $item_id;?>" <?php if (isset($this->params) and $this->params and $item_id==$this->params['team']):?>selected<?php endif;?>><?php echo $item['name'];?></option>
                                <?php endforeach;?>
                            <?php endif ?>
                        </select>
                    </div>

                    <div class="control-group">
                        <label for="title" class="span2">Title</label>
                        <select name="title" id="title" >
                            <option value>Choose</option>
                            <?php if ( isset($this->params) AND isset($this->recursiveDeparmentTeamTitle[$this->params['department']]['children'][$this->params['team']]['children']) ): ?>
                                <?php foreach ($this->recursiveDeparmentTeamTitle[$this->params['department']]['children'][$this->params['team']]['children'] as $item_id => $item):?>
                                    <option value="<?php echo $item_id;?>" <?php if (isset($this->params) and $this->params and $item_id==$this->params['title']):?>selected<?php endif;?>><?php echo $item['name'];?></option>
                                <?php endforeach;?>
                            <?php endif ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <button type="submit" name="export" value="1" class="btn btn-warning mr-2">Export</button>
                <button type="submit" name="export_detail" value="1" class="btn btn-success">Export Detail</button>
            </div>
            </form>
            </div>
        </div>
    </div>
</div>
