<div class="page-header span9">
    <h1>My Check In</h1>
    <div class="pull-right" style="margin-top: -25px">
        <a href="/leave/list-my-leave" class="btn btn-success pull-right" style="margin-right: 0.2em !important" title="My Leave">My Leave</a>
    </div>
</div>

<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message) :
            echo '<div class="alert alert-success">' . $message . '</div>';
        endforeach;

    if (isset($this->messages_error) and $this->messages_error)
        foreach ($this->messages_error as $message) :
            echo '<div class="alert alert-danger">' . $message . '</div>';
        endforeach;
?>

<div class="staff_info span12">
    <h3>
    <?php echo $this->staff_info['code'] . " - " . $this->staff_info['firstname'] . " " . $this->staff_info['lastname']; ?>
    </h3>
</div>

<div class="span12" style="margin-left: 0px">
    <form class="form-group">
        <select class="mr-2" name="month" id="month" style="padding: 6px;">
            <?php for ($i = 1; $i <= 12; $i ++) { ?>
            <option value="<?php echo $i; ?>" <?php echo ($this->params['month'] == $i) ? ' selected ' : '' ?>>Tháng <?php echo $i; ?></option>
            <?php } ?>
        </select> 
        <input class="mr-2" type="number" id="year" name="year" value="<?php echo $this->params['year'] ?>">
        <button class="btn btn-primary">Tìm kiếm</button>
    </form>
</div>

<div  class="span9" style="margin-left: 0px">
    <table class="table table-responsive">
        <thead>
            <th>Ngày đi làm</th>
            <th>Phép năm tính lương</th>
            <th>Ngày off</th>
            <th><span>Số lần quên chấm công</span></th>
            <th><span>Tổng thời gian đi trễ</span></th>
            <th><span>Số ngày phạt</span></th>
        </thead>
        <tbody>
            <tr>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
            </tr>
        </tbody>
    </table>

    <table class="table table-bordered table-responsive">
        <thead>
            <tr>
            <th>Ngày</th>
            <th>Giờ vào</th>
            <th>Giờ ra</th>
            <th>Ngày công</th>
            <th>Lý do</th>
            <th>Ghi chú</th>
            <th>Bổ sung công </th>
            </tr>
        </thead>
        <tbody>
            <?php 
            if( isset($this->list) and $this->list ) {
                foreach ($this->list as $key => $value) {             
                    $day_to_vi = array(
                        1 => 'Chủ nhật',
                        2 => 'Thứ hai',
                        3 => 'Thứ ba',
                        4 => 'Thứ tư',
                        5 => 'Thứ năm',
                        6 => 'Thứ sáu',
                        7 => 'Thứ bảy'
                    );                    
            ?>            
            <tr>
                <td>
                    <?php echo $day_to_vi[$value['day_of_week']]." ,<br/>ngày ".date_format(date_create($value['date']), "d/m/Y"); ?>
                </td>
                <td><?php echo $value['check_in_at'] ? date_format(date_create($value['check_in_at']), "d/m/Y H:i:s") : ""; ?></td>
                <td><?php echo $value['check_out_at'] ? date_format(date_create($value['check_out_at']), "d/m/Y H:i:s") : ""; ?></td>
                <td>
                    <?php
                        if ($value['time_number'] > 6) {
                            echo "1 ngày công";
                        } elseif ($value['time_number'] < 6 && $value['time_number'] > 2) {
                            echo "0.5 ngày công";
                        } 
                    ?>
                </td>
                <td></td>
                <td></td>
                <td>
                <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"> Bổ
                        sung <span class=""></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php if ($value['time_number'] < 6) { ?>
                            <li><a class="" href="#"><i class="icon-file"></i> Bổ sung công </a></li>
                            <li><a class="" href="#"><i class="icon-list-alt"></i> Bổ sung phép </a></li>
                        <?php } ?>                        
                        <?php if ($value['late'] == 1 || $value['soon'] == 1) { ?>
                        <li><a class="" href="#"><i class="icon-edit"></i> Xác nhận đi trễ / về sớm </a></li>
                        <?php } ?>
                    </ul>
                </td>
            </tr>    
            <?php  } 
                }
            ?>
        </tbody>
    </table>
</div>

