<div class="page-header">
    <h3>Job Title</h3>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">' . $message . '</div>';
    endforeach;
if (isset($this->message_success) and $this->message_success)
    foreach ($this->message_success as $message):
        echo '<div class="alert alert-success">' . $message . '</div>';
    endforeach;
?>

<div class="row-fluid">
    <div class="span12">
        <form action="/staff/job-title" name="search-form" id="search-form" method="post">
            <div class="control-group span12">
                <input type="hidden" name="department" id="department_id"/>
                <input type="hidden" name="team" id="team_id"/>
                <input type="hidden" name="title" id="title_id"/>
                <button type="submit" name="export" value="1" class="btn btn-success">Export All</button>
            </div>
        </form>
    </div>
</div>

<div class="row-fluid span12">
    <div class="input-prepend span4">
        <div class="btn-group">
            <button class="btn" tabindex="-1">Department</button>
            <button class="btn dropdown-toggle" data-toggle="dropdown" tabindex="-1">
                <span class=""></span>
            </button>
            <ul class="dropdown-menu">
                <li><a id="add_department" href="#addDepartment" data-toggle="modal">Add Department</a></li>
                <li><a id="edit_department" href="#editDepartment" data-toggle="modal">Edit Department</a></li>
                <li><a id="del_department" href="#delDepartment" data-toggle="modal">Delete Department</a></li>
            </ul>
            <select name="department" id="department" class="span2">
                <option value=""></option>
                <?php if (isset($this->listDepartment) and ( $this->listDepartment)): ?>
                    <?php foreach ($this->listDepartment as $key => $value): ?>
                        <option value="<?php echo $value['id'] ?>" rel="<?php echo $value['name'] ?>"><?php echo $value['name'] ?></option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
        </div>
    </div>
    <div class="input-prepend span4">
        <div class="btn-group">
            <button class="btn" tabindex="-1">Team</button>
            <button class="btn dropdown-toggle" data-toggle="dropdown" tabindex="-1">
                <span class=""></span>
            </button>
            <ul class="dropdown-menu">
                <li><a class="team" id="add_team" href="#addTeam" data-toggle="modal">Add Team</a></li>
                <li><a class="team" id="edit_team" href="#editTeam" data-toggle="modal">Edit Team</a></li>
                <li><a class="team" id="delete_team" href="#deleteTeam" data-toggle="modal">Delete Team </a></li>
            </ul>
            <select name="team" id="team" class="span2">
                <option value=""></option>
            </select>
        </div>
    </div>
    <div class="input-prepend span4">
        <div class="btn-group">
            <button class="btn" tabindex="-1">Job Title</button>
            <button class="btn dropdown-toggle" data-toggle="dropdown" tabindex="-1">
                <span class=""></span>
            </button>
            <ul class="dropdown-menu">
                <li><a id="add_job_title" href="#addJobTitle" data-toggle="modal">Add Job Title</a></li>
                <li><a id="edit_job_tile" href="#editJobTitle" data-toggle="modal">Edit Job Title</a></li>
                <li><a id="delete_job_title" href="#deleteJobTitle" data-toggle="modal">Delete Job Title </a></li>
            </ul>
            <select name="job_title" id="job_title" class="span2">
                <option value=""></option>
            </select>
        </div>
    </div>    
</div>

<script>
    $(document).ready(function () {
        getTeam();
        getJobTitle();
    });

    function getTeam()
    {
        $('#department').change(function () {
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var departmentID = $('#department').val();
            $.ajax
            ({
                url: '/ajax/get-team',
                type: 'get',
                data: {'department_id': departmentID},
                dataType: 'json',
                success: function (result)
                {
                    $('#team').find('option:not(:first)').remove();
                    $('#job_title').find('option:not(:first)').remove();
                    $.each(result, function (i, item) {
                        $('#team').append('<option value="' + item.id + '" rel="' + item.name + '">' + item.name + '</option>');
                    });
                },
                error: function ()
                {
                    alert("Not Found !!!");
                }

            });
            $('.loading').remove();
        });
    }

    function getJobTitle()
    {
        $('#team').change(function () {
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var teamID = $('#team').val();        
            $.ajax
            ({
                url: '/ajax/get-job-title',
                type: 'get',
                data: {'team_id': teamID},
                dataType: 'json',
                success: function (result)
                {
                    $('#job_title').find('option:not(:first)').remove();
                    $.each(result, function (i, item) {
                        $('#job_title').append('<option value="' + item.id +'">' + item.name + '</option>');
                    });
                },
                error: function ()
                {
                    alert("Not Found!!!");
                }
            });
            $('.loading').remove();
        });
    }
</script>