<div class="page-header">
    <h1>List Staff's Photo</h1>
</div>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php echo $this->render('staff/partials/search-list-photo.phtml') ?>
            </div>
        </div>
    </div>
</div>

<?php
if (isset($this->messages_success) and $this->messages_success)
    foreach ($this->messages_success as $message):
        echo '<div class="alert alert-light-success fade show">' . $message . '</div>';
    endforeach;
if (isset($this->messages_error) and $this->messages_error)
    foreach ($this->messages_error as $message):
        echo '<div class="alert alert-light-danger fade show">' . $message . '</div>';
    endforeach;
?>

<?php echo $this->render( 'staff/partials/list-photo.phtml' ) ?>