<div class="row-fluid">
    <div class="span9">
        <div class="control-group">
            <label for="title">Title</label>
            <input type="text" class="form-control span9" id="title" name="title" required="required" value="<?php if (isset($this->notification)): echo $this->notification->title; endif;?>">
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label for="content">Content</label>
            <textarea name="content" id="content"><?php isset($this->notification) and print($this->notification->content);?></textarea>
        </div>
    </div>
</div>
