<div class="row-fluid">
    <div class="span6">
        <div class="control-group">
            <label for="">Important Notification:</label>
            <p>
                <label class="checkbox"><input type="checkbox" name="pop_up" value="1" <?php if (isset($this->notification['pop_up']) && $this->notification['pop_up']) echo "checked" ?>> <strong>Pop-up</strong></label>
            </p>
            <p>
                <label class="checkbox"><input type="checkbox" name="all_staff" value="1" <?php if (isset($this->all_staff) && $this->all_staff) echo "checked" ?>> <strong>All Staff</strong></label>
            </p>
        </div>

        <div class="control-group">
            <label for="">Notify Departments / Teams / Titles:</label>
            <ul class="tree">
                <?php if (isset($this->team_cache) && $this->team_cache): ?>
                    <?php foreach ($this->team_cache as $_department_id => $_department): ?>
                        <li>
                            <input type="checkbox" name="departments[]" value="<?php echo $_department_id;?>" <?php if (isset($this->old_department_objects) && in_array($_department_id, $this->old_department_objects)) echo "checked" ?>> <label class="checkbox"><strong><?php echo $_department['name'];?></strong></label>

                            <?php if (isset($_department['children']) && count($_department['children'])): ?>
                                <ul>
                                <?php foreach ($_department['children'] as $_team_id => $_team): ?>
                                    <li>
                                        <input type="checkbox" name="teams[]" value="<?php echo $_team_id ?>"  <?php if (isset($this->old_team_objects) && in_array($_team_id, $this->old_team_objects)) echo "checked" ?>> <label class="checkbox"><i><u><?php echo $_team['name'];?></u></i></label>

                                        <?php if (isset($_team['children']) && count($_team['children'])): ?>
                                            <ul>
                                            <?php foreach ($_team['children'] as $_title_id => $_title): ?>
                                                <li>
                                                    <input type="checkbox" name="staff_titles[]" value="<?php echo $_title_id ?>"  <?php if (isset($this->old_title_objects) && in_array($_title_id, $this->old_title_objects)) echo "checked" ?>> <label class="checkbox"><?php echo $_title['name'];?></label>
                                                </li>
                                            <?php endforeach ?>
                                            </ul>
                                        <?php endif ?>
                                    </li>
                                <?php endforeach ?>
                                </ul>
                            <?php endif ?>
                        </li>
                    <?php endforeach ?>
                <?php endif ?>
            </ul>            
        </div>
    </div>
</div>