<div class="footer">
    <div class="footer-inner">
        <div class="container">
            <div class="row">
                <div class="span9"> &copy; 2013 OPPO Mobile VN  <?php if (defined("VERSION")) echo " - Version " ,VERSION ?></div>
                <div class="span3" style="text-align: right;"> Support: <strong>(08) 39202555 ( Ext: 119 )</strong> </div>
                <!-- /span12 -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /footer-inner -->
</div>
<!-- /footer -->