<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Login - HR Website</title>
	<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">	
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="icon" type="image/ico" href="/img/favicon.ico" />
    <link href="/css/font-awesome.css" rel="stylesheet">
    <link href="/css/layout_metronic2020/css/plugins_login.bundle.css" rel="stylesheet" type="text/css"/>
    <link href="/css/layout_metronic2020/css/style_login.bundle.min.css" rel="stylesheet" type="text/css"/>
    <link href="/css/layout_metronic2020/css/login_metronic.css" rel="stylesheet" type="text/css"/>                    
</head>

<body>
<?php echo $this->layout()->content; ?>
<script src="/js/jquery-1.7.2.min.js"></script>
<script src="/js/bootstrap.js"></script>
<script src="/js/signin.js"></script>
<script>
var KTAppSettings = {
    "breakpoints": {
        "sm": 576,
        "md": 768,
        "lg": 992,
        "xl": 1200,
        "xxl": 1400
    },
    "colors": {
        "theme": {
            "base": {
                "white": "#ffffff",
                "primary": "#3699FF",
                "secondary": "#E5EAEE",
                "success": "#1BC5BD",
                "info": "#8950FC",
                "warning": "#FFA800",
                "danger": "#F64E60",
                "light": "#E4E6EF",
                "dark": "#181C32"
            },
            "light": {
                "white": "#ffffff",
                "primary": "#E1F0FF",
                "secondary": "#EBEDF3",
                "success": "#C9F7F5",
                "info": "#EEE5FF",
                "warning": "#FFF4DE",
                "danger": "#FFE2E5",
                "light": "#F3F6F9",
                "dark": "#D6D6E0"
            },
            "inverse": {
                "white": "#ffffff",
                "primary": "#ffffff",
                "secondary": "#3F4254",
                "success": "#ffffff",
                "info": "#ffffff",
                "warning": "#ffffff",
                "danger": "#ffffff",
                "light": "#464E5F",
                "dark": "#ffffff"
            }
        },
        "gray": {
            "gray-100": "#F3F6F9",
            "gray-200": "#EBEDF3",
            "gray-300": "#E4E6EF",
            "gray-400": "#D1D3E0",
            "gray-500": "#B5B5C3",
            "gray-600": "#7E8299",
            "gray-700": "#5E6278",
            "gray-800": "#3F4254",
            "gray-900": "#181C32"
        }
    },
    "font-family": "Poppins"
};
</script>
<script src="/css/layout_metronic2020/js/scripts.bundle.min.js"></script>
<script src="/css/layout_metronic2020/js/login_general.js"></script>
</body>
</html>
