<style>
.maxim{
    color: white; 
    width: auto;
    float: left;
    margin-left: 11%;
    margin-top: 4px;
    margin-bottom: auto;
    text-align: center;
    font-size: 14px; 
    border-radius: 18px;
    border-radius: 18px; 
    padding-right: 5px;
    padding-left: 5px;
    font-weight: bold;
}
@media screen and (min-width: 1200px) {
    .maxim {
        display: block !important;
    }
}
.lunar-alert {
    background: url(/img/CENTER-DANGKYQUATET.png) center   !important;
     background-size: cover !important;
}
.lunar-alert .swal2-image{
    position: relative !important;
    top:30px;
}
.lunar-alert .swal2-confirm{
    background-color: rgba(4,106,56,1) !important;
}
.lunar-alert .swal2-textarea{
    border: 1px solid #e2735e !important ;
    background-color: #fff !important;
}
.lunar-alert .swal2-actions{
    position: relative;
    margin-bottom: 5px;
    top:-20px;
}

</style>
            <?php 
                $userStorage = Zend_Auth::getInstance()->getStorage()->read();
            ?>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container"> 
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <?php if (isset($this->recent_notifications) && count($this->recent_notifications) > 0): ?>
                    <span class="badge badge-important"><?php echo count($this->recent_notifications) ?></span>
                <?php else: ?>
                    <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span> 
                <?php endif ?>
            </a>
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="badge badge-important">5</span>
                <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span> 
            </a>
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span> </a><a class="brand" href="/">
              
            </a>
            
            <div class="div_maxim" >
               <!-- <i  class="maxim"  style=" display: none;" ></i>-->
            </div>

            
<!-- Lunar new year 2019 2020 -->

<!--             <div id="button-gift" style='float:left;<?= (!empty($userStorage->flatAlert)) ? "" : "display: none;"; ?>'>
                <div class="user-config page-name" style="max-width:500px;padding:0px 10px">
                    <div>
                        <img class="lunar-content" style="height: 30px;" src="<?= HOST ?>public\img\text2020.gif">
                        <img class="lunar-content" style="height: 50px; position: absolute;"
                             src="<?= HOST ?>public\img\giphy.gif">
                        <i class="icon-large icon-gift icon-lunar" style="color: red; font-size: 2rem"> </i>
                    </div>
                </div>
                <input name="staffCode" id="staffCode" value="<?php echo $userStorage->code ?>" style="display: none">
            </div> -->
<!-- --------------------------------------------- -->



            <div class="nav-collapse">

                <ul class="nav pull-right">








                    <?php $userStorage = Zend_Auth::getInstance()->getStorage()->read();
                    if ($userStorage->group_id == ADMINISTRATOR_ID):
                    
                        ?>
                        
                        <li><a href="/manage/cache?del=1">Clear cache </a></li>

                    <?php endif; ?>
                    <!--  -->
<?php //echo $this->render('notification-list.phtml')  ?>
                    <!--  -->

                    <li class="dropdown notifi_menu">
                        <a href="javascript:;" class="dropdown-toggle menu-badge " data-toggle="dropdown">

                            <i class="icon-globe"></i>
                        </a>
                        <ul class="dropdown-menu menu-notification">
                            <li><a href="#"><i>No recent notification</i></a></li>

                            <li><a href="<?php echo HOST; ?>user/notification" class="see-all">See All</a></li>
                        </ul></li>
                    <li class="dropdown"><a href="#"id="click-show" class="dropdown-toggle" data-toggle="dropdown"><i
                                class="icon-user"></i> <?php echo $this->name; ?> </a>
                        <ul class="dropdown-menu">
                            <li><a href="/user-information">User Information</a></li>
                            <li><a href="/user/change-pass">Change password</a></li>
                            <li><a href="/user/logout">Logout</a></li>
                        </ul>
                    </li>
                </ul>
                <!--
                <form class="navbar-search pull-right">
                    <input type="text" class="search-query" placeholder="Search">
                </form>
                -->
            </div>
            <!--/.nav-collapse -->
        </div>
        <!-- /container -->
    </div>
    <!-- /navbar-inner -->
</div>
<script type="text/javascript" src="/js/sweetalert2.all.min.js"></script>

<script>
$(document).ready(function () {
	initCountNotification();
	initNotification(); 
        getMaxim();
});

    function initCountNotification() {
        $.ajax({
            type: 'get',
            url: '/ajax/count-noti',
            error: function (error) {
                console.log(eval(error));
            },
            success: function (data) {
            
                if (data > 0) {
                    $('.menu-badge').append('<span class="badge badge-important">' + data + '</span>');
                }
            }
        });

    }
    function initNotification() {
        $.ajax({
            type: 'get',
            url: '/ajax/load-noti',
            error: function (error) {
                console.log(eval(error));
            },
            success: function (data) {
                
                if (!$.isEmptyObject($.parseJSON(data))) {
                    var list_notification = '';
                    var count_noti = 0;
                    $.each($.parseJSON(data), function (i, object) {
                        count_noti++;
                        list_notification = list_notification +
                                '<li><a class="notiupdate" data_noti="' + object.id + '" href="/user/notification-view?id=' + object.id + '"><i>' + object.title + '</i></a></li>';
                    });
                    $('.menu-notification').empty();
                    $('.menu-notification').append(list_notification + '<li><a href="/user/notification" class="see-all">See All</a></li>');


                } else {

                }


            }
        });

    }
    
    
    

    function getMaxim(){
//            $.ajax({
//            type: 'get',
//            url: '/ajax/get-maxim',
//
//            error: function(error){
//                    console.log(eval(error)); 
//            },
//            success: function(data){ 
//                console.log(data); 
//                var response = $.parseJSON(data); 
//                
//                 if (response.status == 1) {
//                            $('.div_maxim').append('<i  class="maxim" style=" display: none;" >'+response.data+'</i>');
//                 }
//            }
//        });

    }

  // Toan Nguyen 5/11/2019
        $("#button-gift").on("click", function () {
        var staffCode=$("#staffCode").val();

        $.ajax({
            method: "GET",
            url: "/collection/status-gift",
            data: {staff_code:staffCode}
        })
            .done(function (output) {
                if (!output) {
                    Swal.fire({
                        customClass:"lunar-alert",
                        title: 'Bạn đã nhận được quà tết Canh Tý chưa?',
                        text: "Phản hồi quà tết:",
                        // type: 'question',
                        // imageUrl:'question',
                        // imageUrl:' ../lunar-year-2020/img/lunar-alert.png',
                        imageUrl:"<?= HOST ?>public/img/chuot2020.png",
                        
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Đã nhận',
                        cancelButtonText: 'Vẫn chưa',
                        input: "textarea"

                    })
                        .then((result) => {
                            if(!result.dismiss){
                                $.ajax({
                                    method: "GET",
                                    url: "/collection/status-gift",
                                    data: {staff_code:staffCode,receive_status:1,feedback:result.value}
                                }).done(function (output1){
                                Swal.fire({
                                    title: 'Xin cảm ơn',
                                    text: "Hệ thống đã ghi nhận lại câu trả lời của bạn.",
                                    // type: 'success',
                                    showCancelButton: false,
                                    confirmButtonColor: '#3085d6',
                                    cancelButtonColor: '#d33',
                                    timer: 1000
                                })
                                })
                            }

                        })
                }else{
                    Swal.fire({
                        title: 'HAPPY NEW YEAR !!!',
                        text: "OPPO kính chúc bạn có một năm mới thật tuyệt vời.",
                        // icon: 'success',
                        showCancelButton: false,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        timer: 2000
                    })
                }
            })
    })

</script>