<div class="page-header">
    <h1>Check Out GPS</h1>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-danger">'.$message.'</div>';
    endforeach;

if (isset($this->messages_success) and $this->messages_success)
    foreach ($this->messages_success as $messages_success):
        echo '<div class="alert alert-success">'.$messages_success.'</div>';
    endforeach;
?>

<form method="POST" action="/user/save-check-out-gps">
    <div class="row pl-5 pl-md-0">
        <div class="col-12 col-md-6 p-0">
            <div class="form-group">
                <label for="staff_name">Ngày chấm công:</label>
                <h5><?php echo date('d/m/Y') ; ?></h5>
            </div>

            <div class="form-group">
                <label for="staff_name">Tên nhân viên:</label>
                <h5><?php isset($this->staff) and $this->staff and printf($this->staff->firstname . " " . $this->staff->lastname);?></h5>
            </div>

            <div class="form-group">
                <label for="staff_code">Mã nhân viên:</label>
                <h5><?php isset($this->staff) and $this->staff and printf($this->staff->code);?></h5>
            </div>

            <span class="text-danger">(*) Bạn đã Check in lúc <?php echo date('H:i:s', strtotime($this->check_in->check_in_at)); ?></span>
        </div>        

        <div class="col-12 col-md-12 p-0">
            <button type="submit" class="btn btn-success mt-5 w-auto h-auto">Check Out</button>
        </div>
    </div>
</form>